# ASCII-Font › http://patorjk.com/software/taag/#p=display&f=Slant&t=Phlow
#
#      _____ _ __          _____      __  __  _                 
#     / ___/(_) /____     / ___/___  / /_/ /_(_)___  ____ ______
#     \__ \/ / __/ _ \    \__ \/ _ \/ __/ __/ / __ \/ __ `/ ___/
#    ___/ / / /_/  __/   ___/ /  __/ /_/ /_/ / / / / /_/ (__  ) 
#   /____/_/\__/\___/   /____/\___/\__/\__/_/_/ /_/\__, /____/  
#                                                 /____/        
#
# Title of your website
title: "MacroSeismic Sensor Netzwerk"


# The slogan describes your website and is used on homepage in <title> and other important places
slogan: "Messung und Visualisierung von Bodenbewegungen."


# The description is used on homepage and in the footer to quickly describe your website. Use a maximum of 150 characters for SEO-purposes.
description: "Messung und Visualisierung von Bodenbewegungen im südlichen Wiener Becken mit Hilfe eines seismischen Netzwerks, das mit low-cost Sensoren betrieben wird."

# Main author of the website
# See > authors.yml
author: stefan

# This URL is the main address for absolute links. Don't include a slash at the end.
#
url: 'https://www.macroseismicsensor.at'

# This is for the editing function in _/includes/improve_content
# Leave it empty if your site is not on GitHub/GitHub Pages
improve_content: 

# This URL points directly to the images directory making
# things easier to link to images in posts and templates. It needs a slash at the end.
#
# Example: <img src="{{ site.urlimg }}{{ post.image.title }}" />
# Markdown-Example for posts ![Image Text]({{ site.urlimg }}image.jpg)
#
assets_dir: '/assets/'
image_dir: '/images/'

# Theme works best with Kramdown (using the table of contents function)
markdown: kramdown
permalink: /:categories/:title/
highlight: rouge
plugins: [jekyll-paginate,
          jekyll-scholar]
excerpt_separator: "<!--more-->"
include: ['.htaccess', '_pages', '_projects']
# Exclude these files from your production _site
exclude:
    - .sass-cache
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - INSTALL.md



#
#
# COLLECTIONS
#
#
collections:
    doc:
        output: true
        #permalink: /document/:name


#
#
# PAGINATION
#
#
# Paginates all X entries
paginate: 10

# Pagination path › Important for blog page in /blog/ to work
paginate_path: "blog/page:num"



# The language setting is used in /includes/header.html for html-settings
#language: "en"


# Used › default.html front-matter and compress.html
# Options › http://jch.penibelst.de
# The environment is set using JEKYLL_ENV when starting the server. Using no
# argument sets JEKYLL_ENV to development.
# The blanklines setting is important to keep inline javascript working.
# Otherwise, comments will comment all the following code, because the whole
# content is put into one line.
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: []
  profile: false
  blanklines: true
  ignore:
    envs: [development]


#
#       ____       ____            ____
#      / __ \___  / __/___ ___  __/ / /_
#     / / / / _ \/ /_/ __ `/ / / / / __/
#    / /_/ /  __/ __/ /_/ / /_/ / / /_
#   /_____/\___/_/  \__,_/\__,_/_/\__/
#
# Default Settings

defaults:
    -
        scope:
            path: "" 			# an empty string here means all files in the project
        values:
            author: Stefan Mertl
            lang: de
            base_url: "/"
            copyright:
                author: "MSS Team"
    -
        scope:
            path: en
        values:
            lang: en
            base_url: "/en/"
    -
        scope:
          path: ""
          type: "posts"
        values:
          lang: de
          layout: page
          header: no
          show_meta: true   # Show metadata for all posts
          comments: false
    -
        scope:
          path: en
          type: "posts"
        values:
          lang: en
          layout: page
          header: no
          show_meta: true   # Show metadata for all posts
          comments: false

    -
        scope:
          path: ""
          type: "doc"
        values:
          license: cc-by-sa-4.0
          
#       ______            _
#      / ____/___ __   __(_)________  ____  _____
#     / /_  / __ `/ | / / / ___/ __ \/ __ \/ ___/
#    / __/ / /_/ /| |/ / / /__/ /_/ / / / (__  )
#   /_/    \__,_/ |___/_/\___/\____/_/ /_/____/   Favicon-Crap: Favicons, Chrome, Android & Apple Touch Buttons
#                                                 More information » https://mathiasbynens.be/notes/touch-icons

favicon-32x32:                          "mss_favicon_32x32.ico"
#touch-icon-192x192:                     "touch-icon-192x192.png"
#apple-touch-icon-180x180-precomposed:   "apple-touch-icon-180x180-precomposed.png"
#apple-touch-icon-152x152-precomposed:   "apple-touch-icon-152x152-precomposed.png"
#apple-touch-icon-144x144-precomposed:   "apple-touch-icon-144x144-precomposed.png"
#apple-touch-icon-120x120-precomposed:   "apple-touch-icon-120x120-precomposed.png"
#apple-touch-icon-114x114-precomposed:   "apple-touch-icon-114x114-precomposed.png"
#apple-touch-icon-76x76-precomposed:     "apple-touch-icon-76x76-precomposed.png"
#apple-touch-icon-72x72-precomposed:     "apple-touch-icon-72x72-precomposed.png"
#apple-touch-icon-precomposed:           "apple-touch-icon-precomposed.png"
#msapplication_tileimage:                "msapplication_tileimage.png"               # Size 144x144
#msapplication_tilecolor:                "#fabb00"


#      _____
#     / ___/____ ___________
#     \__ \/ __ `/ ___/ ___/
#    ___/ / /_/ (__  |__  )     More › http://sass-lang.com/
#   /____/\__,_/____/____/      More › http://jekyllrb.com/docs/assets/#sassscss
#

sass:
    sass_dir: _sass
    style: :compressed


#
#
#
# SCHOLAR
#
#
#
#
scholar:
    style: ./_bibliography/ieee.csl
    locale: de

    source: ./_bibliography
    bibliography: references.bib
    bibliography_template: bibtemplate

    bibliography_list_tag: ul
    bibliography_group_tag: h3

    type_order: [article, phdthesis, inproceedings, techreport, misc]
    type_aliases: {report: techreport}
